// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface

#include "ui.h"

lv_obj_t * ui_ScreenSettings = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_ImgButton2 = NULL;
// event funtions
void ui_event_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMain_screen_init);
        _ui_screen_delete(&ui_ScreenSettings);
    }
}

// build funtions

void ui_ScreenSettings_screen_init(void)
{
    ui_ScreenSettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -112);
    lv_obj_set_y(ui_Label8, -198);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Settings");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton2 = lv_imgbtn_create(ui_ScreenSettings);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1508956403, NULL);
    lv_obj_set_width(ui_ImgButton2, 50);
    lv_obj_set_height(ui_ImgButton2, 52);
    lv_obj_set_x(ui_ImgButton2, -334);
    lv_obj_set_y(ui_ImgButton2, -190);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);

}

void ui_ScreenSettings_screen_destroy(void)
{
    if(ui_ScreenSettings) lv_obj_del(ui_ScreenSettings);

    // NULL screen variables
    ui_ScreenSettings = NULL;
    ui_Label8 = NULL;
    ui_ImgButton2 = NULL;

}
