// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface

#include "ui.h"

lv_obj_t * ui_ScreenMain = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Panel12 = NULL;
lv_obj_t * ui_Switch2 = NULL;
lv_obj_t * ui_Switch3 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Panel13 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_ImgButton1 = NULL;
lv_obj_t * ui_TabView1 = NULL;
lv_obj_t * ui_TabPage1 = NULL;
lv_obj_t * ui_TabPage2 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_Panel11 = NULL;
lv_obj_t * ui_ImgButton3 = NULL;
lv_obj_t * ui_ImgButton4 = NULL;
lv_obj_t * ui_ImgButton5 = NULL;
lv_obj_t * ui_ImgButton6 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_Label33 = NULL;
// event funtions
void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_checked_set_text_value(ui_Label14, target, "On", "Off");
    }
}

void ui_event_Switch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_checked_set_text_value(ui_Label11, target, "On", "Off");
    }
}

void ui_event_Switch3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_checked_set_text_value(ui_Label12, target, "On", "Off");
    }
}

void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSettings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenSettings_screen_init);
        _ui_screen_delete(&ui_ScreenMain);
    }
}

void ui_event_Panel6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_opacity_set(ui_Panel12, 1000);
        _ui_opacity_set(ui_Panel13, 20);
    }
}

void ui_event_Panel7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_opacity_set(ui_Panel13, 1000);
        _ui_opacity_set(ui_Panel12, 20);
    }
}

// build funtions

void ui_ScreenMain_screen_init(void)
{
    ui_ScreenMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -334);
    lv_obj_set_y(ui_Label1, -213);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "IncuNest");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_Panel1, 376);
    lv_obj_set_height(ui_Panel1, 291);
    lv_obj_set_x(ui_Panel1, -201);
    lv_obj_set_y(ui_Panel1, -31);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_Panel2, 376);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_x(ui_Panel2, -201);
    lv_obj_set_y(ui_Panel2, 174);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch1 = lv_switch_create(ui_ScreenMain);
    lv_obj_set_width(ui_Switch1, 100);
    lv_obj_set_height(ui_Switch1, 39);
    lv_obj_set_x(ui_Switch1, -126);
    lv_obj_set_y(ui_Switch1, 174);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    ui_Panel3 = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_Panel3, 341);
    lv_obj_set_height(ui_Panel3, 107);
    lv_obj_set_x(ui_Panel3, 180);
    lv_obj_set_y(ui_Panel3, -110);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel12 = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_Panel12, 342);
    lv_obj_set_height(ui_Panel12, 76);
    lv_obj_set_x(ui_Panel12, -204);
    lv_obj_set_y(ui_Panel12, -89);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel12, lv_color_hex(0x8EA1DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_ScreenMain);
    lv_obj_set_width(ui_Switch2, 100);
    lv_obj_set_height(ui_Switch2, 39);
    lv_obj_set_x(ui_Switch2, -126);
    lv_obj_set_y(ui_Switch2, -150);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    ui_Switch3 = lv_switch_create(ui_ScreenMain);
    lv_obj_set_width(ui_Switch3, 100);
    lv_obj_set_height(ui_Switch3, 39);
    lv_obj_set_x(ui_Switch3, 251);
    lv_obj_set_y(ui_Switch3, -140);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);

    ui_Panel4 = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_Panel4, 336);
    lv_obj_set_height(ui_Panel4, 129);
    lv_obj_set_x(ui_Panel4, 184);
    lv_obj_set_y(ui_Panel4, 33);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel5 = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_Panel5, 332);
    lv_obj_set_height(ui_Panel5, 96);
    lv_obj_set_x(ui_Panel5, 187);
    lv_obj_set_y(ui_Panel5, 163);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -291);
    lv_obj_set_y(ui_Label2, -150);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Temperature control");

    ui_Label3 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -281);
    lv_obj_set_y(ui_Label3, 173);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Phototherapy");

    ui_Panel13 = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_Panel13, 342);
    lv_obj_set_height(ui_Panel13, 76);
    lv_obj_set_x(ui_Panel13, -204);
    lv_obj_set_y(ui_Panel13, 53);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel13, lv_color_hex(0x8EA1DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_Image4, &ui_img_1084506651);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, -97);
    lv_obj_set_y(ui_Image4, -85);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 40);

    ui_Label4 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 100);
    lv_obj_set_y(ui_Label4, -141);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Humidity control");

    ui_Label5 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 89);
    lv_obj_set_y(ui_Label5, -5);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Pulse Oximetry");

    ui_Image2 = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_Image2, &ui_img_bebe_icon_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -91);
    lv_obj_set_y(ui_Image2, 60);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 50);

    ui_Label6 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -359);
    lv_obj_set_y(ui_Label6, -19);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Set");

    ui_ImgButton1 = lv_imgbtn_create(ui_ScreenMain);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_296721678, NULL);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_296721678, NULL);
    lv_obj_set_width(ui_ImgButton1, 58);
    lv_obj_set_height(ui_ImgButton1, 58);
    lv_obj_set_x(ui_ImgButton1, 352);
    lv_obj_set_y(ui_ImgButton1, -201);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);

    ui_TabView1 = lv_tabview_create(ui_ScreenMain, LV_DIR_TOP, 30);
    lv_obj_set_width(ui_TabView1, 262);
    lv_obj_set_height(ui_TabView1, 65);
    lv_obj_set_x(ui_TabView1, 181);
    lv_obj_set_y(ui_TabView1, 161);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "Alarms");

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "View details");

    ui_Label7 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 216);
    lv_obj_set_y(ui_Label7, -90);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Set");

    ui_Label11 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -51);
    lv_obj_set_y(ui_Label11, -150);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Off");

    ui_Label12 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 324);
    lv_obj_set_y(ui_Label12, -141);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Off");

    ui_Label13 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -325);
    lv_obj_set_y(ui_Label13, -85);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "25.1");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -51);
    lv_obj_set_y(ui_Label14, 174);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Off");

    ui_Panel6 = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_Panel6, 61);
    lv_obj_set_height(ui_Panel6, 28);
    lv_obj_set_x(ui_Panel6, -155);
    lv_obj_set_y(ui_Panel6, -19);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0xA9ACF7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -156);
    lv_obj_set_y(ui_Label9, -19);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Air");

    ui_Label10 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -325);
    lv_obj_set_y(ui_Label10, 60);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "28.3");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 47);
    lv_obj_set_y(ui_Label15, -102);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "50");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -239);
    lv_obj_set_y(ui_Label16, -19);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "C");

    ui_Label17 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 327);
    lv_obj_set_y(ui_Label17, -89);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "%");

    ui_Panel7 = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_Panel7, 61);
    lv_obj_set_height(ui_Panel7, 28);
    lv_obj_set_x(ui_Panel7, -79);
    lv_obj_set_y(ui_Panel7, -19);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xA9ACF7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -78);
    lv_obj_set_y(ui_Label18, -19);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Skin");

    ui_Label19 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 99);
    lv_obj_set_y(ui_Label19, 37);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "0");
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 289);
    lv_obj_set_y(ui_Label20, 37);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "lpm");
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -266);
    lv_obj_set_y(ui_Label21, -85);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "C ->");
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -266);
    lv_obj_set_y(ui_Label22, 60);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "C ->");
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 95);
    lv_obj_set_y(ui_Label23, -102);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "% ->");
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 137);
    lv_obj_set_y(ui_Label24, 36);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "%");
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 226);
    lv_obj_set_y(ui_Label25, 38);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "160");
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_Panel8, 36);
    lv_obj_set_height(ui_Panel8, 32);
    lv_obj_set_x(ui_Panel8, -318);
    lv_obj_set_y(ui_Panel8, -19);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel9 = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_Panel9, 36);
    lv_obj_set_height(ui_Panel9, 32);
    lv_obj_set_x(ui_Panel9, -270);
    lv_obj_set_y(ui_Panel9, -19);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel10 = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_Panel10, 36);
    lv_obj_set_height(ui_Panel10, 32);
    lv_obj_set_x(ui_Panel10, 256);
    lv_obj_set_y(ui_Panel10, -89);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel11 = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_Panel11, 36);
    lv_obj_set_height(ui_Panel11, 32);
    lv_obj_set_x(ui_Panel11, 298);
    lv_obj_set_y(ui_Panel11, -88);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton3 = lv_imgbtn_create(ui_ScreenMain);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1497256624, NULL);
    lv_obj_set_width(ui_ImgButton3, 20);
    lv_obj_set_height(ui_ImgButton3, 28);
    lv_obj_set_x(ui_ImgButton3, -320);
    lv_obj_set_y(ui_ImgButton3, -19);
    lv_obj_set_align(ui_ImgButton3, LV_ALIGN_CENTER);

    ui_ImgButton4 = lv_imgbtn_create(ui_ScreenMain);
    lv_imgbtn_set_src(ui_ImgButton4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_145782787, NULL);
    lv_obj_set_width(ui_ImgButton4, 22);
    lv_obj_set_height(ui_ImgButton4, 23);
    lv_obj_set_x(ui_ImgButton4, -271);
    lv_obj_set_y(ui_ImgButton4, -19);
    lv_obj_set_align(ui_ImgButton4, LV_ALIGN_CENTER);

    ui_ImgButton5 = lv_imgbtn_create(ui_ScreenMain);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1497256624, NULL);
    lv_obj_set_width(ui_ImgButton5, 20);
    lv_obj_set_height(ui_ImgButton5, 29);
    lv_obj_set_x(ui_ImgButton5, 253);
    lv_obj_set_y(ui_ImgButton5, -87);
    lv_obj_set_align(ui_ImgButton5, LV_ALIGN_CENTER);

    ui_ImgButton6 = lv_imgbtn_create(ui_ScreenMain);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_145782787, NULL);
    lv_obj_set_width(ui_ImgButton6, 25);
    lv_obj_set_height(ui_ImgButton6, 26);
    lv_obj_set_x(ui_ImgButton6, 299);
    lv_obj_set_y(ui_ImgButton6, -87);
    lv_obj_set_align(ui_ImgButton6, LV_ALIGN_CENTER);

    ui_Label26 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -213);
    lv_obj_set_y(ui_Label26, -85);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "25.5");

    ui_Label27 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -213);
    lv_obj_set_y(ui_Label27, 60);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "28.1");

    ui_Label28 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, -184);
    lv_obj_set_y(ui_Label28, -85);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "C");

    ui_Label29 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -184);
    lv_obj_set_y(ui_Label29, 60);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "C");

    ui_Label30 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, -256);
    lv_obj_set_y(ui_Label30, -115);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "Air");

    ui_Label31 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, -256);
    lv_obj_set_y(ui_Label31, 26);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "Skin");

    ui_Label32 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, 143);
    lv_obj_set_y(ui_Label32, -102);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "50.3");

    ui_Label33 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, 170);
    lv_obj_set_y(ui_Label33, -102);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "%");

    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch3, ui_event_Switch3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel6, ui_event_Panel6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel7, ui_event_Panel7, LV_EVENT_ALL, NULL);

}

void ui_ScreenMain_screen_destroy(void)
{
    if(ui_ScreenMain) lv_obj_del(ui_ScreenMain);

    // NULL screen variables
    ui_ScreenMain = NULL;
    ui_Label1 = NULL;
    ui_Panel1 = NULL;
    ui_Panel2 = NULL;
    ui_Switch1 = NULL;
    ui_Panel3 = NULL;
    ui_Panel12 = NULL;
    ui_Switch2 = NULL;
    ui_Switch3 = NULL;
    ui_Panel4 = NULL;
    ui_Panel5 = NULL;
    ui_Label2 = NULL;
    ui_Label3 = NULL;
    ui_Panel13 = NULL;
    ui_Image4 = NULL;
    ui_Label4 = NULL;
    ui_Label5 = NULL;
    ui_Image2 = NULL;
    ui_Label6 = NULL;
    ui_ImgButton1 = NULL;
    ui_TabView1 = NULL;
    ui_TabPage1 = NULL;
    ui_TabPage2 = NULL;
    ui_Label7 = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;
    ui_Panel6 = NULL;
    ui_Label9 = NULL;
    ui_Label10 = NULL;
    ui_Label15 = NULL;
    ui_Label16 = NULL;
    ui_Label17 = NULL;
    ui_Panel7 = NULL;
    ui_Label18 = NULL;
    ui_Label19 = NULL;
    ui_Label20 = NULL;
    ui_Label21 = NULL;
    ui_Label22 = NULL;
    ui_Label23 = NULL;
    ui_Label24 = NULL;
    ui_Label25 = NULL;
    ui_Panel8 = NULL;
    ui_Panel9 = NULL;
    ui_Panel10 = NULL;
    ui_Panel11 = NULL;
    ui_ImgButton3 = NULL;
    ui_ImgButton4 = NULL;
    ui_ImgButton5 = NULL;
    ui_ImgButton6 = NULL;
    ui_Label26 = NULL;
    ui_Label27 = NULL;
    ui_Label28 = NULL;
    ui_Label29 = NULL;
    ui_Label30 = NULL;
    ui_Label31 = NULL;
    ui_Label32 = NULL;
    ui_Label33 = NULL;

}
