; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = src
boards_dir = .
core_dir = C:\pio
build_dir = C:\pio\.bld

[env:main]
platform = espressif32 @ 6.3.2 ; Stable version for S3-Arduino 2.0.11 or similar
board = esp32-s3-devkitc-1
framework = arduino
; platform_packages not pinned, let platform decide or pin to recent
; platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.14

; Memory Configuration for CrowPanel 7.0 (16MB Flash / 8MB PSRAM OPI)
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.partitions = IncuNest_display_v0.csv

build_flags = 
	-D LV_LVGL_H_INCLUDE_SIMPLE
	-I./include
    -D BOARD_HAS_PSRAM
    -D CORE_DEBUG_LEVEL=5  ; 0 = NONE, desactiva todos los errores
    ;-D ARDUINO_USB_CDC_ON_BOOT=1 ; Uncomment if using USB-C Serial
monitor_speed = 115200

lib_deps = 
	; tamctec/TAMC_GT911@^1.0.2 ; Removed to use local fixed version
    ; ./lib/TAMC_GT911_Fixed ; Auto-detected in lib folder
	moononournation/GFX Library for Arduino@1.2.8
	lovyan03/LovyanGFX@^1.1.12
	maxpromer/PCA9557-arduino@^1.0.0
	adafruit/Adafruit GFX Library@^1.11.9
	lvgl/lvgl@^8.3.11
	https://github.com/thingsboard/thingsboard-arduino-sdk.git#v0.13.0
 	https://github.com/bblanchon/ArduinoStreamUtils.git
	https://github.com/vshymanskyy/StreamDebugger.git
	https://github.com/arduino-libraries/ArduinoMqttClient.git
	https://github.com/ricemices/ArduinoHttpClient.git
	bblanchon/ArduinoJson@6.21.5
  	thingsboard/TBPubSubClient@2.9.4
