SET(SOURCES ui_Screen1.c
    ui_Screen2.c
    ui_Screen3.c
    ui_Screen4.c
    ui_Screen5.c
    ui_Screen6.c
    ui_Screen7.c
    ui.c
    ui_comp_hook.c
    ui_helpers.c
    ui_img_296721678.c
    ui_img_1007688293.c
    ui_img_1084506651.c
    ui_img_1370137984.c
    ui_img_bebe_icon_png.c
    ui_img_triangulo_abajo_png.c
    ui_img_triangulo_arriba_png.c
    ui_img_gota_png.c
    ui_img_candado_png.c
    ui_img_pulse_png.c
    ui_img_chart_png.c
    ui_img_1508956403.c
    ui_img_mute_icon_png.c)

add_library(ui ${SOURCES})
