// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface

#ifndef UI_SCREEN10_H
#define UI_SCREEN10_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen10
extern void ui_Screen10_screen_init(void);
extern void ui_Screen10_screen_destroy(void);
extern lv_obj_t * ui_Screen10;
extern lv_obj_t * ui_Container1;
extern void ui_event_Panel11(lv_event_t * e);
extern lv_obj_t * ui_Panel11;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

