// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface

#include "ui.h"

lv_obj_t * ui_Screen10 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Panel11 = NULL;
// event funtions
void ui_event_Panel11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_delete(&ui_Screen10);
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen10_screen_init(void)
{
    ui_Screen10 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_Screen10);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 775);
    lv_obj_set_height(ui_Container1, 462);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel11 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_Panel11, 788);
    lv_obj_set_height(ui_Panel11, 464);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Panel11, ui_event_Panel11, LV_EVENT_ALL, NULL);

}

void ui_Screen10_screen_destroy(void)
{
    if(ui_Screen10) lv_obj_del(ui_Screen10);

    // NULL screen variables
    ui_Screen10 = NULL;
    ui_Container1 = NULL;
    ui_Panel11 = NULL;

}
