// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface

#include "ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_ImgButton7 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_TabView1 = NULL;
lv_obj_t * ui_TabPage1 = NULL;
lv_obj_t * ui_Alarm1Panel = NULL;
lv_obj_t * ui_Alarm1Label = NULL;
lv_obj_t * ui_Alarm2Panel = NULL;
lv_obj_t * ui_Alarm2Label = NULL;
lv_obj_t * ui_Alarm3Panel = NULL;
lv_obj_t * ui_Alarm3Label = NULL;
lv_obj_t * ui_Alarm4Panel = NULL;
lv_obj_t * ui_Alarm4Label = NULL;
lv_obj_t * ui_TabPage2 = NULL;
lv_obj_t * ui_MuteAlarm = NULL;
// event funtions
void ui_event_ImgButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        _ui_screen_delete(&ui_Screen3);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton7 = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1508956403, NULL);
    lv_obj_set_width(ui_ImgButton7, 50);
    lv_obj_set_height(ui_ImgButton7, 52);
    lv_obj_set_x(ui_ImgButton7, -360);
    lv_obj_set_y(ui_ImgButton7, -204);
    lv_obj_set_align(ui_ImgButton7, LV_ALIGN_CENTER);

    ui_Panel5 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel5, 376);
    lv_obj_set_height(ui_Panel5, 350);
    lv_obj_set_x(ui_Panel5, 194);
    lv_obj_set_y(ui_Panel5, 54);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView1 = lv_tabview_create(ui_Screen3, LV_DIR_TOP, 30);
    lv_obj_set_width(ui_TabView1, 334);
    lv_obj_set_height(ui_TabView1, 326);
    lv_obj_set_x(ui_TabView1, 194);
    lv_obj_set_y(ui_TabView1, 53);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_TabView1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TabView1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "Alarms");

    ui_Alarm1Panel = lv_obj_create(ui_TabPage1);
    lv_obj_set_width(ui_Alarm1Panel, 316);
    lv_obj_set_height(ui_Alarm1Panel, 50);
    lv_obj_set_x(ui_Alarm1Panel, 1);
    lv_obj_set_y(ui_Alarm1Panel, -115);
    lv_obj_set_align(ui_Alarm1Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Alarm1Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Alarm1Panel, lv_color_hex(0xCD3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Alarm1Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm1Label = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Alarm1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alarm1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Alarm1Label, 0);
    lv_obj_set_y(ui_Alarm1Label, -116);
    lv_obj_set_align(ui_Alarm1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alarm1Label, "TEMP MUY ALTA");
    lv_obj_set_style_text_color(ui_Alarm1Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Alarm1Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Alarm1Label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm2Panel = lv_obj_create(ui_TabPage1);
    lv_obj_set_width(ui_Alarm2Panel, 316);
    lv_obj_set_height(ui_Alarm2Panel, 50);
    lv_obj_set_x(ui_Alarm2Panel, 1);
    lv_obj_set_y(ui_Alarm2Panel, -60);
    lv_obj_set_align(ui_Alarm2Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Alarm2Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Alarm2Panel, lv_color_hex(0xCD3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Alarm2Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm2Label = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Alarm2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alarm2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Alarm2Label, 0);
    lv_obj_set_y(ui_Alarm2Label, -60);
    lv_obj_set_align(ui_Alarm2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alarm2Label, "TEMP MUY ALTA");
    lv_obj_set_style_text_color(ui_Alarm2Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Alarm2Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Alarm2Label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm3Panel = lv_obj_create(ui_TabPage1);
    lv_obj_set_width(ui_Alarm3Panel, 316);
    lv_obj_set_height(ui_Alarm3Panel, 50);
    lv_obj_set_x(ui_Alarm3Panel, 1);
    lv_obj_set_y(ui_Alarm3Panel, 0);
    lv_obj_set_align(ui_Alarm3Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Alarm3Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Alarm3Panel, lv_color_hex(0xCD3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Alarm3Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm3Label = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Alarm3Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alarm3Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alarm3Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alarm3Label, "TEMP MUY ALTA");
    lv_obj_set_style_text_color(ui_Alarm3Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Alarm3Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Alarm3Label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm4Panel = lv_obj_create(ui_TabPage1);
    lv_obj_set_width(ui_Alarm4Panel, 316);
    lv_obj_set_height(ui_Alarm4Panel, 50);
    lv_obj_set_x(ui_Alarm4Panel, 1);
    lv_obj_set_y(ui_Alarm4Panel, 60);
    lv_obj_set_align(ui_Alarm4Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Alarm4Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Alarm4Panel, lv_color_hex(0xCD3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Alarm4Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm4Label = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Alarm4Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alarm4Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Alarm4Label, 0);
    lv_obj_set_y(ui_Alarm4Label, 60);
    lv_obj_set_align(ui_Alarm4Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alarm4Label, "TEMP MUY ALTA");
    lv_obj_set_style_text_color(ui_Alarm4Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Alarm4Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Alarm4Label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "View details");

    ui_MuteAlarm = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_MuteAlarm, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_mute_icon_png, NULL);
    lv_obj_set_width(ui_MuteAlarm, 44);
    lv_obj_set_height(ui_MuteAlarm, 45);
    lv_obj_set_x(ui_MuteAlarm, 198);
    lv_obj_set_y(ui_MuteAlarm, 183);
    lv_obj_set_align(ui_MuteAlarm, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton7, ui_event_ImgButton7, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_ImgButton7 = NULL;
    ui_Panel5 = NULL;
    ui_TabView1 = NULL;
    ui_TabPage1 = NULL;
    ui_Alarm1Panel = NULL;
    ui_Alarm1Label = NULL;
    ui_Alarm2Panel = NULL;
    ui_Alarm2Label = NULL;
    ui_Alarm3Panel = NULL;
    ui_Alarm3Label = NULL;
    ui_Alarm4Panel = NULL;
    ui_Alarm4Label = NULL;
    ui_TabPage2 = NULL;
    ui_MuteAlarm = NULL;

}
