[env:IncuNest_V16]
build_flags = 
    -DCORE_DEBUG_LEVEL=3     ; ESP32 Arduino specific: Set to the maximum debug level
    -g3                      ; Generate maximum debugging information
    -O0                      ; Disable optimization to get more accurate debugging
    -DUSER_SETUP_LOADED=1
    -DTFT_INVERSION_ON=1
    -DILI9341_2_DRIVER=1
    -DTFT_MISO=19
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_CS=15
    -DTFT_DC=0
    -DTFT_RST=-1
    -DTOUCH_CS=-1
    -DLOAD_GLCD=1
    -DSPI_FREQUENCY=27000000
    -DBQ25730_TEST
    -D LV_LVGL_H_INCLUDE_SIMPLE
    -I./include
    ; -DARDUINO_USB_MODE=1
    ; -DARDUINO_USB_CDC_ON_BOOT=1
    
    ; -DIN3_DEBUG           ; <-- si quieres tu propio macro
    ; -Wno-attributes       ; <-- opcional, solo si quieres silenciar 'packed'
    ; -Wno-return-type      ; <-- NO recomendado, silencia avisos útiles
    ; -DCRASH_TEST_MB=1

platform = espressif32@6.6.0
framework = arduino
board = esp32-s3-devkitc-1
board_build.partitions = ESP32S3_OTA_partition_8MB.csv
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = dio
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_type = debug
debug_tool = esp-prog
debug_init_break = tbreak setup

lib_deps =
  https://github.com/br3ttb/Arduino-PID-Library.git
  https://github.com/mathertel/RotaryEncoder.git
  https://github.com/adafruit/Adafruit-GFX-Library.git
  https://github.com/adafruit/Adafruit_BusIO.git
  https://github.com/sparkfun/SparkFun_SHTC3_Arduino_Library.git
  https://github.com/thingsboard/thingsboard-arduino-sdk.git#v0.13.0
  https://github.com/bblanchon/ArduinoStreamUtils.git
  https://github.com/vshymanskyy/TinyGSM.git
  https://github.com/vshymanskyy/StreamDebugger.git
  https://github.com/RobTillaart/TCA9555.git
  https://github.com/adafruit/Adafruit_SHT4X.git
  https://github.com/tttapa/Arduino-Filters.git
  https://github.com/medicalopenworld/incunest_afe4490.git#master
  https://github.com/arduino-libraries/ArduinoMqttClient.git
  https://github.com/Bodmer/TFT_eSPI.git
  https://github.com/ricemices/ArduinoHttpClient.git
  https://github.com/Sensirion/arduino-i2c-sts3x.git
  https://github.com/beast-devices/Arduino-INA3221.git
  bblanchon/ArduinoJson@6.21.5
  thingsboard/TBPubSubClient@2.9.4
