#ifndef EEPROM_DEFINES_H
#define EEPROM_DEFINES_H

#define EEPROM_COMMIT_DELAY 10000

// EEPROM variables
#define EEPROM_SIZE 256
#define EEPROM_CHECK_STATUS 0
#define EEPROM_FIRST_TURN_ON 10
#define EEPROM_AUTO_LOCK 20
#define EEPROM_LANGUAGE 30
#define EEPROM_SERIAL_NUMBER 40
#define EEPROM_WIFI_EN 50
#define EEPROM_CONTROL_ACTIVE 60
#define EEPROM_PHOTOTHERAPY_ACTIVE 65
#define EEPROM_CONTROL_MODE 70
#define EEPROM_HEATER_TEST 75
#define EEPROM_DESIRED_AIR_TEMP 80
#define EEPROM_DESIRED_SKIN_TEMP 85
#define EEPROM_DESIRED_HUMIDITY 90
#define EEPROM_RAW_SKIN_TEMP_LOW_CORRECTION 100
#define EEPROM_RAW_SKIN_TEMP_RANGE_CORRECTION 110
#define EEPROM_WIFI_SSID 115
#define EEPROM_WIFI_PASSWORD 145
#define EEPROM_REFERENCE_TEMP_RANGE 170
#define EEPROM_REFERENCE_TEMP_LOW 180
#define EEPROM_FINE_TUNE_TEMP_SKIN 190
#define EEPROM_FINE_TUNE_TEMP_AIR 194
#define EEPROM_THINGSBOARD_PROVISIONED 200
#define EEPROM_THINGSBOARD_TOKEN 205
#define EEPROM_STANDBY_TIME 226
#define EEPROM_CONTROL_ACTIVE_TIME 230
#define EEPROM_HEATER_ACTIVE_TIME 234
#define EEPROM_FAN_ACTIVE_TIME 238
#define EEPROM_PHOTOTHERAPY_ACTIVE_TIME 242
#define EEPROM_HUMIDIFIER_ACTIVE_TIME 246
#define EEPROM_PANIC_OTA_CHANGE 250

void initEEPROM();
void loaddefaultValues();
void recapVariables();
void resetFlash();
#endif