// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface

#ifndef _ESP32HMIINTERFACE_UI_H
#define _ESP32HMIINTERFACE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_Screen3.h"
#include "ui_Screen4.h"
#include "ui_Screen5.h"
#include "ui_Screen6.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_296721678);    // assets/settings icon (2).png
LV_IMG_DECLARE(ui_img_1007688293);    // assets/alarms1 (2).png
LV_IMG_DECLARE(ui_img_1084506651);    // assets/wind-vector.png
LV_IMG_DECLARE(ui_img_1370137984);    // assets/termometro (2).png
LV_IMG_DECLARE(ui_img_bebe_icon_png);    // assets/bebe icon.png
LV_IMG_DECLARE(ui_img_triangulo_abajo_png);    // assets/triangulo_abajo.png
LV_IMG_DECLARE(ui_img_triangulo_arriba_png);    // assets/triangulo_arriba.png
LV_IMG_DECLARE(ui_img_gota_png);    // assets/gota.png
LV_IMG_DECLARE(ui_img_pulse_png);    // assets/pulse.png
LV_IMG_DECLARE(ui_img_chart_png);    // assets/chart.png
LV_IMG_DECLARE(ui_img_1508956403);    // assets/back icon (1).png
LV_IMG_DECLARE(ui_img_mute_icon_png);    // assets/mute_icon.png
LV_IMG_DECLARE(ui_img_candado_png);    // assets/candado.png
LV_IMG_DECLARE(ui_img_302897630);    // assets/water-drop-icon-transparent-free-png.png
LV_IMG_DECLARE(ui_img_windvector_png);    // assets/windVector.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
