// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface_Screen_Intro

#ifndef UI_SCREENINTRO_H
#define UI_SCREENINTRO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenIntro
extern void ui_ScreenIntro_screen_init(void);
extern void ui_ScreenIntro_screen_destroy(void);
extern lv_obj_t * ui_ScreenIntro;
extern lv_obj_t * ui_ImageLogoIncunest;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

