// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel2;
extern void ui_event_Switch3(lv_event_t * e);
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_AirPanel;
extern void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern void ui_event_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_SkinPanel;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label6;
extern void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_TempAirDesired;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_TempSkinDesired;
extern lv_obj_t * ui_HumDetected;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_ArrowDownTemp;
extern lv_obj_t * ui_ArrowUpTemp;
extern lv_obj_t * ui_ArrowDownHum;
extern lv_obj_t * ui_ArrowUpHum;
extern lv_obj_t * ui_ImgArrowDownTemp;
extern lv_obj_t * ui_ImgArrowUpTemp;
extern lv_obj_t * ui_ImgArrowDownHum;
extern lv_obj_t * ui_ImgArrowUpHum;
extern lv_obj_t * ui_TempAirDetected;
extern lv_obj_t * ui_TempSkinDetected;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_HumDesired;
extern lv_obj_t * ui_TempButton;
extern lv_obj_t * ui_HumidButton;
extern lv_obj_t * ui_Alarm1Panel;
extern lv_obj_t * ui_Alarm1Label;
extern lv_obj_t * ui_Alarm2Panel;
extern lv_obj_t * ui_Alarm2Label;
extern lv_obj_t * ui_Alarm3Panel;
extern lv_obj_t * ui_Alarm3Label;
extern lv_obj_t * ui_Alarm4Panel;
extern lv_obj_t * ui_Alarm4Label;
extern lv_obj_t * ui_Mutealarm;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Tempbutton;
extern lv_obj_t * uic_HumidButton;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

