// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface_Screen6

#ifndef UI_SCREEN6_H
#define UI_SCREEN6_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen6
extern void ui_Screen6_screen_init(void);
extern void ui_Screen6_screen_destroy(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_LockButton;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_AirTempLockCont;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_SkinTempLockCont;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_HumLockCont;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_HumLockDesiredCont;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_LockButton2;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Spinner1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

