#pragma once
// Task priorities, periods, and core assignments

#define CORE_MONITOR_FREERTOS 0
#define CORE_ID_FREERTOS 1

// Tasks priorities
#define POWER_MANAGEMENT_TASK_PRIORITY 1
#define TIME_TRACK_TASK_PRIORITY 2
// Telemetria auxiliar: por debajo de GPRS y del enlace con la HMI a
// proposito, nada de lo que trae el SensorBoard entra en el lazo de control.
#define SENSORBOARD_TASK_PRIORITY 3
#define OTA_TASK_PRIORITY 4
#define GPRS_TAST_PRIORITY 5
#define BUZZER_TASK_PRIORITY 6
#define COMMUNICATION_TASK_PRIORITY 7
#define COMMUNICATION_RECEIVER_PRIORITY 7
#define SENSORS_TASK_PRIORITY 8
#define SPO2_TASK_PRIORITY 8
#define SECURITY_TASK_PRIORITY 9
#define GPRS_MONITOR_TASK_PRIORITY 10

#define PWR_HOLD_MS 3000
#define PWR_OFF_UPDATE_INTERVAL_MS 200
#define POWER_MANAGEMENT_TASK_PERIOD_MS 50

#define GPRS_TASK_PERIOD_MS 1
#define OTA_TASK_PERIOD_MS 50
#define SENSORS_TASK_PERIOD_MS 1
#define SPO2_TASK_PERIOD_MS 1
#define SKIN_SENSOR_UPDATE_PERIOD_MS 200 // in millis
#define ROOM_SENSOR_UPDATE_PERIOD_MS 1000
#define ROOM_SENSOR_RECONNECT_MS     500
#define PHOTOTHERAPY_INITIAL_PWM_PCT 40
#define PHOTO_TARGET_CURRENT 0.45f
#define PHOTO_SETTLE_MS      3000
#define PHOTO_CONTROL_PERIOD_MS 1000
#define PHOTO_MAX_STEP       1
#define PHOTO_TOLERANCE_A    0.02f
#define PHOTO_MIN_PWM        10
#define DIGITAL_CURRENT_SENSOR_PERIOD_MS 5
#define BUZZER_TASK_PERIOD_MS 10
#define SECURITY_TASK_PERIOD_MS 1
#define COMMUNICATION_TASK_PERIOD_MS 1
// 1 s basta: el heartbeat del SensorBoard es de 30 s y su margen de 90 s.
#define SENSORBOARD_TASK_PERIOD_MS 1000
#define TIME_TRACK_TASK_PERIOD_MS 100
#define FAN_TASK_PERIOD_MS 10
#define LOOP_TASK_PERIOD_MS 1000
#define GPRS_MONITOR_TASK_PERIOD 5000
#define GPRS_MONITOR_TASK_DELETE 30000
