#pragma once
// ThingsBoard telemetry key strings

#define SN_KEY "SN"
#define HW_NUM_KEY "HW_num"
#define HW_REV_KEY "HW_revision"
#define FW_VERSION_KEY "FW_version"
#define CCID_KEY "CCID"
#define IMEI_KEY "IMEI"
#define APN_KEY "APN"
#define COP_KEY "COP"
#define SYSTEM_RESET_REASON "RST_reason"
#define SYS_CURR_STANDBY_TEST_KEY "SYS_current_stanby_test"
#define HEATER_CURR_TEST_KEY "Heater_current_test"
#define FAN_CURR_TEST_KEY "Fan_current_test"
#define PHOTOTHERAPY_CURR_KEY "Phototherapy_current_test"
#define HUMIDIFIER_CURR_KEY "Humidifier_current_test"
#define BUZZER_CURR_TEST_KEY "Buzzer_current_test"
#define HW_TEST_KEY "HW_Test"
#define LOCATION_LONGTITUD_KEY "tri_longitud"
#define LOCATION_LATITUD_KEY "tri_latitud"
#define TRI_ACCURACY_KEY "tri_accuracy"
#define UI_LANGUAGE_KEY "UI_language"
// Skin_CAP retired: raw capacitance was a bring-up diagnostic, not
// clinical data. The probe state already travels in CTRL,TEL.
#define SKIN_TEMPERATURE_KEY "Skin_temp"
#define AIR_TEMPERATURE_KEY "Air_temp"
#define AIR_TEMPERATURE_REDUNDANT_KEY "Air_temp_redundant"
#define AMBIENT_TEMPERATURE_KEY "Amb_temp"
#define HUMIDITY_ROOM_KEY "Humidity"
#define HUMIDITY_AMBIENT_KEY "Amb_humidity"
#define SYSTEM_CURRENT_KEY "SYS_current"
#define SYSTEM_VOLTAGE_KEY "SYS_voltage"
#define CELL_SIGNAL_QUALITY_KEY "CSQ"
#define HEATER_CURRENT_KEY "Heater_current"
#define FAN_CURRENT_KEY "Fan_current"
#define FAN_FEEDBACK_PRESENT_KEY "fan_has_fb"
#define FAN_RPM_KEY "fan_rpm"
#define FAN_PWM_KEY "fan_pwm"  // applied fan control duty, raw 0-255 counts
#define V5_CURRENT_KEY "V5_current"
#define V5_VOLTAGE_KEY "V5_voltage"
#define BAT_CURRENT_KEY "BAT_current"
#define BAT_VOLTAGE_KEY "BAT_voltage"
#define CONTROL_ACTIVE_KEY "Control_active"
#define CONTROL_MODE_KEY "Control_mode"
#define DESIRED_TEMPERATURE_KEY "Temp_desired"
#define DESIRED_HUMIDITY_ROOM_KEY "Hum_desired"
#define HUMIDIFIER_CURRENT_KEY "Humidifier_current"
#define HUMIDIFIER_VOLTAGE_KEY "Humidifier_voltage"
#define PHOTOTHERAPY_PWM_KEY "PH_PWM"
#define PHOTOTHERAPY_CURRENT_KEY "Phototherapy_current"
#define PHOTOTHERAPY_ACTIVE_KEY "Phototherapy_active"
#define CALIBRATED_SENSOR_KEY "Calibrated_sensor"
#define STANBY_TIME_KEY "Standby_time"
#define CONTROL_ACTIVE_TIME_KEY "Control_active_time"
#define HEATER_ACTIVE_TIME_KEY "Heater_active_time"
#define FAN_ACTIVE_TIME_KEY "Fan_active_time"
#define PHOTHERAPY_ACTIVE_TIME_KEY "Phototherapy_active_time"
#define HUMIDIFIER_ACTIVE_TIME_KEY "Humidifier_active_time"
#define GPRS_CONNECTIVITY_KEY "GPRS_connection"
#define WIFI_CONNECTIVITY_KEY "WIFI_connection"
#define HR1_KEY "HR1"
#define HR1_SQI_KEY "HR1_SQI"
#define HR2_KEY "HR2"
#define HR2_SQI_KEY "HR2_SQI"
#define HR3_KEY "HR3"
#define HR3_SQI_KEY "HR3_SQI"
#define SPO2_KEY "SpO2"
#define SPO2_SQI_KEY "SpO2_SQI"
#define PI_KEY "PI"
// _v1: versionado por si cambia el formato (fs/duración/canal) más adelante.
#define PPG_SNAPSHOT_KEY "PPG_snapshot_v1"       // 1 punto por muestra ppg_disp
#define PPG_SNAPSHOT_FS_KEY "PPG_snapshot_fs_v1" // sample rate de la captura [Hz]
#define PPG_SNAPSHOT_N_KEY "PPG_snapshot_n_v1"   // nº de muestras de la última captura
#define BABY_WEIGHT_KEY "baby_weight_g"
#define BABY_GEST_AGE_KEY "baby_gest_weeks"
#define BABY_AGE_DAYS_KEY "baby_age_days"
// Intentional PII publication (Ministry of Health access via ThingsBoard) —
// see openspec design decision 14; not an accidental leak.
#define BABY_NAME_KEY "baby_name"
#define BABY_OUTCOME_KEY "baby_outcome"
#define BABY_DISCHARGE_EPOCH_KEY "baby_discharge_epoch"
#define BABY_KANGAROO_COUNT_KEY "baby_kangaroo_count"
#define BABY_KANGAROO_LAST_KEY "baby_kangaroo_last_epoch"
#define BABY_PHOTO_MINUTES_KEY "baby_phototherapy_min"
#define BABY_THERMO_MINUTES_KEY "baby_thermo_min"
#define BABY_HUMIDITY_MINUTES_KEY "baby_humidity_min"
// baby_seq is mandatory on every baby payload: without it the cloud cannot
// tell one patient from the next, and per-baby cumulative counters look
// like data corruption when a new admission resets them.
#define BABY_SEQ_KEY "baby_seq"
#define BABY_ADMISSION_EPOCH_KEY "baby_admission_epoch"
#define BABY_KANGAROO_EVENT_KEY "baby_kangaroo_event"
#define BABY_STAY_DAYS_KEY "baby_stay_days"
#define HUMIDITY_ALARM_KEY "hum_alarm"
#define TEMPERATURE_ALARM_KEY "temp_alarm"
#define AIR_THERMAL_CUTOUT_ALARM_KEY "air_TC_alarm"
#define SKIN_THERMAL_CUTOUT_ALARM_KEY "skin_TC_alarm"
#define AIR_SENSOR_ISSUE_ALARM_KEY "air_sensor_alarm"
#define SKIN_SENSOR_ISSUE_ALARM_KEY "skin_sensor_alarm"
#define FAN_ISSUE_ALARM_KEY "fan_alarm"
#define HEATER_ISSUE_ALARM_KEY "heater_alarm"
#define POWER_SUPPLY_ALARM_KEY "power_alarm"
#define AIR_BLOCKED_ALARM_KEY "air_blocked_alarm"

#define CALIBRATION_RAW_TEMPERATURE_RANGE_SKIN_KEY "Cal_raw_range_skin_temp"
#define CALIBRATION_RAW_TEMPERATURE_LOW_SKIN_KEY "Cal_raw_low_skin_temp"
#define CALIBRATION_REFERENCE_TEMPERATURE_RANGE_KEY "Cal_ref_range_temp"
#define CALIBRATION_REFERENCE_TEMPERATURE_LOW_KEY "Cal_ref_low_temp"
#define CALIBRATION_SKIN_FINETUNE_KEY "Cal_finetune_skin_temp"
#define CALIBRATION_AIR_FINETUNE_KEY "Cal_finetune_air_temp"

// Diagnostic telemetry keys
// BQ25730 charger telemetry keys
#define BQ_STATE_KEY  "BQ_state"
#define BQ_FAULT_KEY  "BQ_fault"
#define BQ_AC_KEY     "BQ_ac"
#define BQ_VBAT_KEY   "BQ_vbat_V"
#define BQ_VBUS_KEY   "BQ_vbus_V"
#define BQ_ICHG_KEY   "BQ_ichg_mA"

#define BOOT_COUNT_KEY "boot_count"
#define FREE_HEAP_KEY "free_heap"
#define MIN_FREE_HEAP_KEY "min_free_heap"
#define UPTIME_S_KEY "uptime_s"
#define GPRS_KILL_COUNT_KEY "gprs_kill_count"
#define GPRS_MON_KILL_COUNT_KEY "gprs_mon_kill_count"
#define HMI_BOOT_COUNT_KEY "hmi_boot_count"
#define HMI_LAST_RST_KEY "hmi_last_rst"
