// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface

#ifndef UI_ScreenLock_H
#define UI_ScreenLock_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenLock
extern void ui_ScreenLock_screen_init(void);
extern void ui_ScreenLock_screen_destroy(void);
extern lv_obj_t * ui_ScreenLock;
extern void ui_event_ImgButton10(lv_event_t * e);
extern lv_obj_t * ui_ImgButton10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

