// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface

#ifndef UI_ScreenCharts_H
#define UI_ScreenCharts_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenCharts
extern void ui_ScreenCharts_screen_init(void);
extern void ui_ScreenCharts_screen_destroy(void);
extern lv_obj_t * ui_ScreenCharts;
extern void ui_event_ImgButton8(lv_event_t * e);
extern lv_obj_t * ui_ImgButton8;
extern lv_obj_t * ui_HumChartCont;
extern lv_obj_t * ui_HumChart;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_OxChartCont;
extern lv_obj_t * ui_OxChart;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_TempChartCont;
extern lv_obj_t * ui_TempChart;
extern lv_obj_t * ui_Label37;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

