// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern void ui_event_ImgButton7(lv_event_t * e);
extern lv_obj_t * ui_ImgButton7;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_AlarmsTabview;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_Alarm1Cont;
extern lv_obj_t * ui_Alarm1Panel;
extern lv_obj_t * ui_Alarm1Label;
extern lv_obj_t * ui_Alarm2Cont;
extern lv_obj_t * ui_Alarm2Panel;
extern lv_obj_t * ui_Alarm2Label;
extern lv_obj_t * ui_Alarm3Cont;
extern lv_obj_t * ui_Alarm3Panel;
extern lv_obj_t * ui_Alarm3Label;
extern lv_obj_t * ui_Alarm4Cont;
extern lv_obj_t * ui_Alarm4Panel;
extern lv_obj_t * ui_Alarm4Label;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_AlarmDetailLabel;
extern lv_obj_t * ui_MuteAlarm;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

