// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface

#ifndef UI_SCREEN5_H
#define UI_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen5
extern void ui_Screen5_screen_init(void);
extern void ui_Screen5_screen_destroy(void);
extern lv_obj_t * ui_Screen5;
extern void ui_event_ImgButton9(lv_event_t * e);
extern lv_obj_t * ui_ImgButton9;
extern lv_obj_t * ui_OxCont;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_DetectOxi;
extern void ui_event_OxiButton2(lv_event_t * e);
extern lv_obj_t * ui_OxiButton2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

