// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface_Screen_Main

#ifndef UI_ScreenPulseOxi_H
#define UI_ScreenPulseOxi_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenPulseOxi
extern void ui_ScreenPulseOxi_screen_init(void);
extern void ui_ScreenPulseOxi_screen_destroy(void);
extern lv_obj_t * ui_ScreenPulseOxi;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

