// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface_Screen_Main

#include "ui.h"

lv_obj_t * ui_ScreenCharts = NULL;
// event funtions

// build funtions

void ui_ScreenCharts_screen_init(void)
{
    ui_ScreenCharts = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenCharts, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_ScreenCharts_screen_destroy(void)
{
    if(ui_ScreenCharts) lv_obj_del(ui_ScreenCharts);

    // NULL screen variables
    ui_ScreenCharts = NULL;

}
