// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface_Screen_Main

#include "ui.h"

lv_obj_t * ui_ScreenAlarms = NULL;
// event funtions

// build funtions

void ui_ScreenAlarms_screen_init(void)
{
    ui_ScreenAlarms = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenAlarms, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_ScreenAlarms_screen_destroy(void)
{
    if(ui_ScreenAlarms) lv_obj_del(ui_ScreenAlarms);

    // NULL screen variables
    ui_ScreenAlarms = NULL;

}
