// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface_Screen_Main

#ifndef UI_SCREENLOCK_H
#define UI_SCREENLOCK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenLock
extern void ui_ScreenLock_screen_init(void);
extern void ui_ScreenLock_screen_destroy(void);
extern lv_obj_t * ui_ScreenLock;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

