// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface_Screen_Charts

#ifndef UI_ScreenCharts_H
#define UI_ScreenCharts_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenCharts
extern void ui_ScreenCharts_screen_init(void);
extern void ui_ScreenCharts_screen_destroy(void);
extern lv_obj_t * ui_ScreenCharts;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TempChartPage1;
extern lv_obj_t * ui_AirTempChartCont;
extern lv_obj_t * ui_AirTempChart;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_SkinTempChartCont;
extern lv_obj_t * ui_SkinTempChart;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_HumChartPage2;
extern lv_obj_t * ui_HumChartCont;
extern lv_obj_t * ui_HumChart;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_OxChartCont;
extern lv_obj_t * ui_OxChart;
extern lv_obj_t * ui_Label35;
extern void ui_event_ImgButton8(lv_event_t * e);
extern lv_obj_t * ui_ImgButton8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

