// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface_Screen_Lock

#ifndef _ESP32HMIINTERFACE_SCREEN_LOCK_UI_H
#define _ESP32HMIINTERFACE_SCREEN_LOCK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_ScreenLock.h"
#include "ui_ScreenMain.h"
#include "ui_ScreenAlarms.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_candado_png);    // assets/candado.png
LV_IMG_DECLARE(ui_img_windvector_png);    // assets/windVector.png
LV_IMG_DECLARE(ui_img_bebe_icon_png);    // assets/bebe icon.png
LV_IMG_DECLARE(ui_img_302897630);    // assets/water-drop-icon-transparent-free-png.png
LV_IMG_DECLARE(ui_img_flecha_png);    // assets/Flecha.png
LV_IMG_DECLARE(ui_img_1007688293);    // assets/alarms1 (2).png
LV_IMG_DECLARE(ui_img_check_png);    // assets/check.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
