// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface_Screen_Lock

#ifndef UI_SCREENALARMS_H
#define UI_SCREENALARMS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenAlarms
extern void ui_ScreenAlarms_screen_init(void);
extern void ui_ScreenAlarms_screen_destroy(void);
extern lv_obj_t * ui_ScreenAlarms;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

