#include "alarm_text.h"

// Ingles es el idioma de reserva: cualquier idioma sin traduccion propia
// (hoy, PORTUGUESE) cae aqui en vez de quedarse sin texto.
#define ES(s) if (lang == SPANISH) return (s)
#define FR(s) if (lang == FRENCH) return (s)

const char *alarm_title_text(AlarmId id, Language lang) {
  switch (id) {
    case ALARM_AIR_THERMAL_CUTOUT:
      ES("CORTE TERMICO AIRE");
      FR("COUPURE THERMIQUE AIR");
      return "AIR THERMAL CUTOUT";
    case ALARM_SKIN_THERMAL_CUTOUT:
      ES("CORTE TERMICO PIEL");
      FR("COUPURE THERMIQUE PEAU");
      return "SKIN THERMAL CUTOUT";
    case ALARM_AIR_SENSOR_FAULT:
      ES("FALLO SENSOR AIRE");
      FR("PANNE CAPTEUR AIR");
      return "AIR SENSOR FAULT";
    case ALARM_SKIN_SENSOR_FAULT_SKIN_MODE:
      ES("FALLO SONDA PIEL");
      FR("PANNE SONDE PEAU");
      return "SKIN PROBE FAULT";
    case ALARM_FAN_FAILURE:
      ES("FALLO VENTILADOR");
      FR("PANNE VENTILATEUR");
      return "FAN FAILURE";
    case ALARM_AIR_OUTLET_BLOCKED:
      ES("SALIDA DE AIRE OBSTRUIDA");
      FR("SORTIE D'AIR OBSTRUEE");
      return "AIR OUTLET BLOCKED";
    case ALARM_MAINS_INTERRUPTION:
      ES("CORTE DE RED");
      FR("COUPURE SECTEUR");
      return "MAINS INTERRUPTION";
    case ALARM_AIR_TEMP_DEVIATION_HIGH:
      ES("TEMP AIRE ALTA");
      FR("TEMP AIR ELEVEE");
      return "AIR TEMP HIGH";
    case ALARM_AIR_TEMP_DEVIATION_LOW:
      ES("TEMP AIRE BAJA");
      FR("TEMP AIR BASSE");
      return "AIR TEMP LOW";
    case ALARM_SKIN_TEMP_DEVIATION_HIGH:
      ES("TEMP PIEL ALTA");
      FR("TEMP PEAU ELEVEE");
      return "SKIN TEMP HIGH";
    case ALARM_SKIN_TEMP_DEVIATION_LOW:
      ES("TEMP PIEL BAJA");
      FR("TEMP PEAU BASSE");
      return "SKIN TEMP LOW";
    case ALARM_HEATER_FAULT:
      ES("FALLO CALENTADOR");
      FR("PANNE CHAUFFAGE");
      return "HEATER FAULT";
    case ALARM_SUPPLY_UNDERVOLTAGE:
      ES("TENSION BAJA");
      FR("TENSION BASSE");
      return "SUPPLY UNDERVOLTAGE";
    case ALARM_HMI_LINK_LOST:
      ES("SIN ENLACE PANTALLA");
      FR("LIAISON ECRAN PERDUE");
      return "DISPLAY LINK LOST";
    case ALARM_SKIN_SENSOR_FAULT_AIR_MODE:
      ES("SONDA PIEL NO VALIDA");
      FR("SONDE PEAU INVALIDE");
      return "SKIN PROBE UNUSABLE";
    case ALARM_HUMIDITY_DEVIATION:
      ES("DESVIACION HUMEDAD");
      FR("ECART HUMIDITE");
      return "HUMIDITY DEVIATION";
    default:
      return "ALARM";
  }
}

const char *alarm_action_text(AlarmId id, Language lang) {
  switch (id) {
    case ALARM_AIR_THERMAL_CUTOUT:
    case ALARM_SKIN_THERMAL_CUTOUT:
      ES("CALEFACTOR CORTADO - REVISAR AL BEBE");
      FR("CHAUFFAGE COUPE - VERIFIER LE BEBE");
      return "HEATER CUT - CHECK THE BABY";
    case ALARM_AIR_SENSOR_FAULT:
      ES("SIN MEDIDA DE AIRE - CONTROL DETENIDO");
      FR("PAS DE MESURE D AIR - CONTROLE ARRETE");
      return "NO AIR READING - CONTROL STOPPED";
    case ALARM_SKIN_SENSOR_FAULT_SKIN_MODE:
      ES("REVISAR SONDA O PASAR A MODO AIRE");
      FR("VERIFIER LA SONDE OU PASSER EN MODE AIR");
      return "CHECK PROBE OR SWITCH TO AIR MODE";
    case ALARM_FAN_FAILURE:
      ES("SIN CIRCULACION DE AIRE - REVISAR EQUIPO");
      FR("PAS DE CIRCULATION D AIR - VERIFIER");
      return "NO AIR CIRCULATION - SERVICE UNIT";
    case ALARM_AIR_OUTLET_BLOCKED:
      ES("DESPEJAR LA SALIDA DE AIRE");
      FR("DEGAGER LA SORTIE D AIR");
      return "CLEAR THE AIR OUTLET";
    case ALARM_MAINS_INTERRUPTION:
      ES("REVISAR LA CONEXION A LA RED");
      FR("VERIFIER LE RACCORDEMENT SECTEUR");
      return "CHECK THE MAINS CONNECTION";
    case ALARM_AIR_TEMP_DEVIATION_HIGH:
      ES("AIRE MAS DE 3 C SOBRE LA CONSIGNA");
      FR("AIR A PLUS DE 3 C AU DESSUS DE LA CONSIGNE");
      return "AIR OVER 3 C ABOVE SETPOINT";
    case ALARM_AIR_TEMP_DEVIATION_LOW:
      ES("AIRE MAS DE 3 C BAJO LA CONSIGNA");
      FR("AIR A PLUS DE 3 C SOUS LA CONSIGNE");
      return "AIR OVER 3 C BELOW SETPOINT";
    case ALARM_SKIN_TEMP_DEVIATION_HIGH:
      ES("PIEL MAS DE 1 C SOBRE LA CONSIGNA");
      FR("PEAU A PLUS DE 1 C AU DESSUS DE LA CONSIGNE");
      return "SKIN OVER 1 C ABOVE SETPOINT";
    case ALARM_SKIN_TEMP_DEVIATION_LOW:
      ES("PIEL MAS DE 1 C BAJO LA CONSIGNA");
      FR("PEAU A PLUS DE 1 C SOUS LA CONSIGNE");
      return "SKIN OVER 1 C BELOW SETPOINT";
    case ALARM_HEATER_FAULT:
      ES("EL EQUIPO NO CALIENTA - REVISAR EQUIPO");
      FR("L APPAREIL NE CHAUFFE PAS - VERIFIER");
      return "UNIT NOT HEATING - SERVICE UNIT";
    case ALARM_SUPPLY_UNDERVOLTAGE:
      ES("REVISAR FUENTE Y CABLEADO");
      FR("VERIFIER L ALIMENTATION ET LE CABLAGE");
      return "CHECK SUPPLY AND WIRING";
    case ALARM_HMI_LINK_LOST:
      ES("DATOS NO FIABLES - REVISAR AL BEBE");
      FR("DONNEES NON FIABLES - VERIFIER LE BEBE");
      return "DATA UNRELIABLE - CHECK THE BABY";
    case ALARM_SKIN_SENSOR_FAULT_AIR_MODE:
      ES("SIN TEMP DE PIEL - MODO AIRE ACTIVO");
      FR("PAS DE TEMP PEAU - MODE AIR ACTIF");
      return "NO SKIN TEMP - AIR MODE ACTIVE";
    case ALARM_HUMIDITY_DEVIATION:
      ES("REVISAR DEPOSITO DE AGUA");
      FR("VERIFIER LE RESERVOIR D EAU");
      return "CHECK THE WATER TANK";
    default:
      return "alarm";
  }
}

#undef ES
#undef FR
