// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface_Screen_Intro

#include "ui.h"

lv_obj_t * ui_ScreenIntro = NULL;
// event funtions

// build funtions

void ui_ScreenIntro_screen_init(void)
{
    ui_ScreenIntro = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenIntro, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_ScreenIntro_screen_destroy(void)
{
    if(ui_ScreenIntro) lv_obj_del(ui_ScreenIntro);

    // NULL screen variables
    ui_ScreenIntro = NULL;

}
