// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface_Screen_Alarms

#include "ui.h"

lv_obj_t * ui_ScreenAlarms = NULL;
lv_obj_t * ui_ImgButton7 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_AlarmsTabview = NULL;
lv_obj_t * ui_TabPage1 = NULL;
lv_obj_t * ui_Alarm1Cont = NULL;
lv_obj_t * ui_Alarm1Panel = NULL;
lv_obj_t * ui_Alarm1Label = NULL;
lv_obj_t * ui_Alarm2Cont = NULL;
lv_obj_t * ui_Alarm2Panel = NULL;
lv_obj_t * ui_Alarm2Label = NULL;
lv_obj_t * ui_Alarm3Cont = NULL;
lv_obj_t * ui_Alarm3Panel = NULL;
lv_obj_t * ui_Alarm3Label = NULL;
lv_obj_t * ui_Alarm4Cont = NULL;
lv_obj_t * ui_Alarm4Panel = NULL;
lv_obj_t * ui_Alarm4Label = NULL;
lv_obj_t * ui_TabPage2 = NULL;
lv_obj_t * ui_AlarmDetailLabel = NULL;
lv_obj_t * ui_MuteAlarm = NULL;
// event funtions
void ui_event_ImgButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMain_screen_init);
        _ui_screen_delete(&ui_ScreenAlarms);
    }
}

// build funtions

void ui_ScreenAlarms_screen_init(void)
{
    ui_ScreenAlarms = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenAlarms, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton7 = lv_imgbtn_create(ui_ScreenAlarms);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1508956403, NULL);
    lv_obj_set_width(ui_ImgButton7, 50);
    lv_obj_set_height(ui_ImgButton7, 52);
    lv_obj_set_x(ui_ImgButton7, -360);
    lv_obj_set_y(ui_ImgButton7, -204);
    lv_obj_set_align(ui_ImgButton7, LV_ALIGN_CENTER);

    ui_Panel5 = lv_obj_create(ui_ScreenAlarms);
    lv_obj_set_width(ui_Panel5, 768);
    lv_obj_set_height(ui_Panel5, 396);
    lv_obj_set_x(ui_Panel5, 17);
    lv_obj_set_y(ui_Panel5, 71);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AlarmsTabview = lv_tabview_create(ui_ScreenAlarms, LV_DIR_TOP, 30);
    lv_obj_set_width(ui_AlarmsTabview, 743);
    lv_obj_set_height(ui_AlarmsTabview, 364);
    lv_obj_set_x(ui_AlarmsTabview, 0);
    lv_obj_set_y(ui_AlarmsTabview, 32);
    lv_obj_set_align(ui_AlarmsTabview, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AlarmsTabview, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_AlarmsTabview, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_AlarmsTabview, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage1 = lv_tabview_add_tab(ui_AlarmsTabview, "");

    ui_Alarm1Cont = lv_obj_create(ui_TabPage1);
    lv_obj_remove_style_all(ui_Alarm1Cont);
    lv_obj_set_width(ui_Alarm1Cont, 712);
    lv_obj_set_height(ui_Alarm1Cont, 50);
    lv_obj_set_x(ui_Alarm1Cont, 0);
    lv_obj_set_y(ui_Alarm1Cont, -115);
    lv_obj_set_align(ui_Alarm1Cont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Alarm1Cont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Alarm1Panel = lv_obj_create(ui_Alarm1Cont);
    lv_obj_set_width(ui_Alarm1Panel, 737);
    lv_obj_set_height(ui_Alarm1Panel, 50);
    lv_obj_set_align(ui_Alarm1Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Alarm1Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Alarm1Panel, lv_color_hex(0xCD3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Alarm1Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm1Label = lv_label_create(ui_Alarm1Cont);
    lv_obj_set_width(ui_Alarm1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alarm1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Alarm1Label, 1);
    lv_obj_set_y(ui_Alarm1Label, 0);
    lv_obj_set_align(ui_Alarm1Label, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_Alarm1Label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm2Cont = lv_obj_create(ui_TabPage1);
    lv_obj_remove_style_all(ui_Alarm2Cont);
    lv_obj_set_width(ui_Alarm2Cont, 712);
    lv_obj_set_height(ui_Alarm2Cont, 50);
    lv_obj_set_x(ui_Alarm2Cont, 0);
    lv_obj_set_y(ui_Alarm2Cont, -59);
    lv_obj_set_align(ui_Alarm2Cont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Alarm2Cont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Alarm2Panel = lv_obj_create(ui_Alarm2Cont);
    lv_obj_set_width(ui_Alarm2Panel, 737);
    lv_obj_set_height(ui_Alarm2Panel, 50);
    lv_obj_set_align(ui_Alarm2Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Alarm2Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Alarm2Panel, lv_color_hex(0xCD3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Alarm2Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm2Label = lv_label_create(ui_Alarm2Cont);
    lv_obj_set_width(ui_Alarm2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alarm2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alarm2Label, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_Alarm2Label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm3Cont = lv_obj_create(ui_TabPage1);
    lv_obj_remove_style_all(ui_Alarm3Cont);
    lv_obj_set_width(ui_Alarm3Cont, 712);
    lv_obj_set_height(ui_Alarm3Cont, 50);
    lv_obj_set_align(ui_Alarm3Cont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Alarm3Cont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Alarm3Panel = lv_obj_create(ui_Alarm3Cont);
    lv_obj_set_width(ui_Alarm3Panel, 737);
    lv_obj_set_height(ui_Alarm3Panel, 50);
    lv_obj_set_align(ui_Alarm3Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Alarm3Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Alarm3Panel, lv_color_hex(0xCD3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Alarm3Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm3Label = lv_label_create(ui_Alarm3Cont);
    lv_obj_set_width(ui_Alarm3Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alarm3Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alarm3Label, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_Alarm3Label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm4Cont = lv_obj_create(ui_TabPage1);
    lv_obj_remove_style_all(ui_Alarm4Cont);
    lv_obj_set_width(ui_Alarm4Cont, 712);
    lv_obj_set_height(ui_Alarm4Cont, 50);
    lv_obj_set_x(ui_Alarm4Cont, 0);
    lv_obj_set_y(ui_Alarm4Cont, 59);
    lv_obj_set_align(ui_Alarm4Cont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Alarm4Cont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Alarm4Panel = lv_obj_create(ui_Alarm4Cont);
    lv_obj_set_width(ui_Alarm4Panel, 737);
    lv_obj_set_height(ui_Alarm4Panel, 50);
    lv_obj_set_align(ui_Alarm4Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Alarm4Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Alarm4Panel, lv_color_hex(0xCD3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Alarm4Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm4Label = lv_label_create(ui_Alarm4Cont);
    lv_obj_set_width(ui_Alarm4Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alarm4Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alarm4Label, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_Alarm4Label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage2 = lv_tabview_add_tab(ui_AlarmsTabview, "");

    ui_AlarmDetailLabel = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_AlarmDetailLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlarmDetailLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmDetailLabel, -277);
    lv_obj_set_y(ui_AlarmDetailLabel, -139);
    lv_obj_set_align(ui_AlarmDetailLabel, LV_ALIGN_CENTER);

    ui_MuteAlarm = lv_imgbtn_create(ui_ScreenAlarms);
    lv_imgbtn_set_src(ui_MuteAlarm, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_mute_icon_png, NULL);
    lv_obj_set_width(ui_MuteAlarm, 44);
    lv_obj_set_height(ui_MuteAlarm, 45);
    lv_obj_set_x(ui_MuteAlarm, 9);
    lv_obj_set_y(ui_MuteAlarm, 171);
    lv_obj_set_align(ui_MuteAlarm, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton7, ui_event_ImgButton7, LV_EVENT_ALL, NULL);

}

void ui_ScreenAlarms_screen_destroy(void)
{
    if(ui_ScreenAlarms) lv_obj_del(ui_ScreenAlarms);

    // NULL screen variables
    ui_ScreenAlarms = NULL;
    ui_ImgButton7 = NULL;
    ui_Panel5 = NULL;
    ui_AlarmsTabview = NULL;
    ui_TabPage1 = NULL;
    ui_Alarm1Cont = NULL;
    ui_Alarm1Panel = NULL;
    ui_Alarm1Label = NULL;
    ui_Alarm2Cont = NULL;
    ui_Alarm2Panel = NULL;
    ui_Alarm2Label = NULL;
    ui_Alarm3Cont = NULL;
    ui_Alarm3Panel = NULL;
    ui_Alarm3Label = NULL;
    ui_Alarm4Cont = NULL;
    ui_Alarm4Panel = NULL;
    ui_Alarm4Label = NULL;
    ui_TabPage2 = NULL;
    ui_AlarmDetailLabel = NULL;
    ui_MuteAlarm = NULL;

}
