// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface_Screen_Charts

#include "ui.h"

lv_obj_t * ui_ScreenCharts = NULL;
lv_obj_t * ui_TabView1 = NULL;
lv_obj_t * ui_TempChartPage1 = NULL;
lv_obj_t * ui_AirTempChartCont = NULL;
lv_obj_t * ui_AirTempChart = NULL;
lv_obj_t * ui_Label37 = NULL;
lv_obj_t * ui_SkinTempChartCont = NULL;
lv_obj_t * ui_SkinTempChart = NULL;
lv_obj_t * ui_Label38 = NULL;
lv_obj_t * ui_HumChartPage2 = NULL;
lv_obj_t * ui_HumChartCont = NULL;
lv_obj_t * ui_HumChart = NULL;
lv_obj_t * ui_Label36 = NULL;
lv_obj_t * ui_OxChartCont = NULL;
lv_obj_t * ui_OxChart = NULL;
lv_obj_t * ui_Label35 = NULL;
lv_obj_t * ui_ImgButton8 = NULL;
// event funtions
void ui_event_ImgButton8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMain_screen_init);
        _ui_screen_delete(&ui_ScreenCharts);
    }
}

// build funtions

void ui_ScreenCharts_screen_init(void)
{
    ui_ScreenCharts = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenCharts, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView1 = lv_tabview_create(ui_ScreenCharts, LV_DIR_TOP, 30);
    lv_obj_set_width(ui_TabView1, 769);
    lv_obj_set_height(ui_TabView1, 403);
    lv_obj_set_x(ui_TabView1, 0);
    lv_obj_set_y(ui_TabView1, 28);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempChartPage1 = lv_tabview_add_tab(ui_TabView1, "TEMPERATURE");

    ui_AirTempChartCont = lv_obj_create(ui_TempChartPage1);
    lv_obj_remove_style_all(ui_AirTempChartCont);
    lv_obj_set_width(ui_AirTempChartCont, 771);
    lv_obj_set_height(ui_AirTempChartCont, 389);
    lv_obj_set_align(ui_AirTempChartCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AirTempChartCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AirTempChart = lv_chart_create(ui_AirTempChartCont);
    lv_obj_set_width(ui_AirTempChart, 637);
    lv_obj_set_height(ui_AirTempChart, 287);
    lv_obj_set_x(ui_AirTempChart, -1);
    lv_obj_set_y(ui_AirTempChart, -1);
    lv_obj_set_align(ui_AirTempChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_AirTempChart, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_AirTempChart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_AirTempChart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_AirTempChart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_AirTempChart_series_1 = lv_chart_add_series(ui_AirTempChart, lv_color_hex(0x808080),
                                                                       LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_AirTempChart_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_AirTempChart, ui_AirTempChart_series_1, ui_AirTempChart_series_1_array);

    ui_Label37 = lv_label_create(ui_AirTempChartCont);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, -2);
    lv_obj_set_y(ui_Label37, -165);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "AIR TEMPERATURE CHART");
    lv_obj_set_style_text_font(ui_Label37, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SkinTempChartCont = lv_obj_create(ui_TempChartPage1);
    lv_obj_remove_style_all(ui_SkinTempChartCont);
    lv_obj_set_width(ui_SkinTempChartCont, 771);
    lv_obj_set_height(ui_SkinTempChartCont, 389);
    lv_obj_set_align(ui_SkinTempChartCont, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SkinTempChartCont, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_SkinTempChartCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SkinTempChart = lv_chart_create(ui_SkinTempChartCont);
    lv_obj_set_width(ui_SkinTempChart, 637);
    lv_obj_set_height(ui_SkinTempChart, 287);
    lv_obj_set_x(ui_SkinTempChart, -1);
    lv_obj_set_y(ui_SkinTempChart, -1);
    lv_obj_set_align(ui_SkinTempChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_SkinTempChart, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_SkinTempChart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_SkinTempChart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_SkinTempChart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_SkinTempChart_series_1 = lv_chart_add_series(ui_SkinTempChart, lv_color_hex(0x808080),
                                                                        LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_SkinTempChart_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_SkinTempChart, ui_SkinTempChart_series_1, ui_SkinTempChart_series_1_array);

    ui_Label38 = lv_label_create(ui_SkinTempChartCont);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, -2);
    lv_obj_set_y(ui_Label38, -165);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "SKIN TEMPERATURE CHART");
    lv_obj_set_style_text_font(ui_Label38, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumChartPage2 = lv_tabview_add_tab(ui_TabView1, "HUMIDITY");

    ui_HumChartCont = lv_obj_create(ui_HumChartPage2);
    lv_obj_remove_style_all(ui_HumChartCont);
    lv_obj_set_width(ui_HumChartCont, 776);
    lv_obj_set_height(ui_HumChartCont, 400);
    lv_obj_set_x(ui_HumChartCont, 1);
    lv_obj_set_y(ui_HumChartCont, 0);
    lv_obj_set_align(ui_HumChartCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HumChartCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HumChart = lv_chart_create(ui_HumChartCont);
    lv_obj_set_width(ui_HumChart, 637);
    lv_obj_set_height(ui_HumChart, 287);
    lv_obj_set_x(ui_HumChart, 0);
    lv_obj_set_y(ui_HumChart, 3);
    lv_obj_set_align(ui_HumChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_HumChart, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_HumChart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_HumChart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_HumChart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_HumChart_series_1 = lv_chart_add_series(ui_HumChart, lv_color_hex(0x808080),
                                                                   LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_HumChart_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_HumChart, ui_HumChart_series_1, ui_HumChart_series_1_array);

    ui_Label36 = lv_label_create(ui_HumChartCont);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, -2);
    lv_obj_set_y(ui_Label36, -165);
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "HUMIDITY CHART");
    lv_obj_set_style_text_font(ui_Label36, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OxChartCont = lv_obj_create(ui_ScreenCharts);
    lv_obj_remove_style_all(ui_OxChartCont);
    lv_obj_set_width(ui_OxChartCont, 775);
    lv_obj_set_height(ui_OxChartCont, 468);
    lv_obj_set_align(ui_OxChartCont, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OxChartCont, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_OxChartCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OxChart = lv_chart_create(ui_OxChartCont);
    lv_obj_set_width(ui_OxChart, 637);
    lv_obj_set_height(ui_OxChart, 336);
    lv_obj_set_x(ui_OxChart, 0);
    lv_obj_set_y(ui_OxChart, 10);
    lv_obj_set_align(ui_OxChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_OxChart, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_OxChart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_OxChart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_OxChart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_OxChart_series_1 = lv_chart_add_series(ui_OxChart, lv_color_hex(0x808080),
                                                                  LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_OxChart_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_OxChart, ui_OxChart_series_1, ui_OxChart_series_1_array);

    ui_Label35 = lv_label_create(ui_OxChartCont);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, -2);
    lv_obj_set_y(ui_Label35, -202);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "OXIMETRY CHART");
    lv_obj_set_style_text_font(ui_Label35, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton8 = lv_imgbtn_create(ui_ScreenCharts);
    lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1508956403, NULL);
    lv_obj_set_width(ui_ImgButton8, 50);
    lv_obj_set_height(ui_ImgButton8, 52);
    lv_obj_set_x(ui_ImgButton8, -360);
    lv_obj_set_y(ui_ImgButton8, -204);
    lv_obj_set_align(ui_ImgButton8, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton8, ui_event_ImgButton8, LV_EVENT_ALL, NULL);

}

void ui_ScreenCharts_screen_destroy(void)
{
    if(ui_ScreenCharts) lv_obj_del(ui_ScreenCharts);

    // NULL screen variables
    ui_ScreenCharts = NULL;
    ui_TabView1 = NULL;
    ui_TempChartPage1 = NULL;
    ui_AirTempChartCont = NULL;
    ui_AirTempChart = NULL;
    ui_Label37 = NULL;
    ui_SkinTempChartCont = NULL;
    ui_SkinTempChart = NULL;
    ui_Label38 = NULL;
    ui_HumChartPage2 = NULL;
    ui_HumChartCont = NULL;
    ui_HumChart = NULL;
    ui_Label36 = NULL;
    ui_OxChartCont = NULL;
    ui_OxChart = NULL;
    ui_Label35 = NULL;
    ui_ImgButton8 = NULL;

}
