// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface_Screen_Lock

#include "ui.h"

lv_obj_t * ui_ScreenLock = NULL;
lv_obj_t * ui_LockButton = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_AirTempLockCont = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_ImageWindLS = NULL;
lv_obj_t * ui_SkinTempLockCont = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_ImageBabyLS = NULL;
lv_obj_t * ui_HumLockCont = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_ImagenWaterLS = NULL;
lv_obj_t * ui_HumLockDesiredCont = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_ArrowHumLock = NULL;
lv_obj_t * ui_UnlockCont = NULL;
lv_obj_t * ui_Panel11 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_LockButton2 = NULL;
lv_obj_t * ui_TargetSkinTempCont = NULL;
lv_obj_t * ui_TargetSkinTempLabel = NULL;
lv_obj_t * ui_TargetSkinTempNumLabel = NULL;
lv_obj_t * ui_ArrowSkinLock = NULL;
lv_obj_t * ui_Spinner1 = NULL;
lv_obj_t * ui_TargetAirTempCont = NULL;
lv_obj_t * ui_TargetAirTempLabel = NULL;
lv_obj_t * ui_TargetAirTempNumLabel = NULL;
lv_obj_t * ui_ArrowAirLock = NULL;
lv_obj_t * ui_StatusCont = NULL;
lv_obj_t * ui_StatusLabel = NULL;
lv_obj_t * ui_AlarmLockCont = NULL;
lv_obj_t * ui_AlarmLockImg = NULL;
lv_obj_t * ui_PanelLockAlarm = NULL;
lv_obj_t * ui_AlarmLockNumLabel = NULL;
lv_obj_t * ui_CheckImg = NULL;
// event funtions
void ui_event_AlarmLockImg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_delete(&ui_ScreenLock);
        _ui_screen_change(&ui_ScreenAlarms, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenAlarms_screen_init);
    }
}

// build funtions

void ui_ScreenLock_screen_init(void)
{
    ui_ScreenLock = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenLock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenLock, lv_color_hex(0x242323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenLock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LockButton = lv_imgbtn_create(ui_ScreenLock);
    lv_imgbtn_set_src(ui_LockButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_candado_png, NULL);
    lv_obj_set_width(ui_LockButton, 38);
    lv_obj_set_height(ui_LockButton, 44);
    lv_obj_set_x(ui_LockButton, -3);
    lv_obj_set_y(ui_LockButton, -213);
    lv_obj_set_align(ui_LockButton, LV_ALIGN_CENTER);

    ui_Container1 = lv_obj_create(ui_ScreenLock);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 775);
    lv_obj_set_height(ui_Container1, 464);
    lv_obj_set_x(ui_Container1, -1);
    lv_obj_set_y(ui_Container1, 1);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AirTempLockCont = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_AirTempLockCont);
    lv_obj_set_width(ui_AirTempLockCont, 262);
    lv_obj_set_height(ui_AirTempLockCont, 134);
    lv_obj_set_x(ui_AirTempLockCont, -245);
    lv_obj_set_y(ui_AirTempLockCont, -112);
    lv_obj_set_align(ui_AirTempLockCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AirTempLockCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_AirTempLockCont);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -34);
    lv_obj_set_y(ui_Label11, -48);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "AIR TEMPERATURE:");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_AirTempLockCont);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 24);
    lv_obj_set_y(ui_Label18, 3);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "37");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageWindLS = lv_img_create(ui_AirTempLockCont);
    lv_img_set_src(ui_ImageWindLS, &ui_img_windvector_png);
    lv_obj_set_width(ui_ImageWindLS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWindLS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWindLS, -93);
    lv_obj_set_y(ui_ImageWindLS, 3);
    lv_obj_set_align(ui_ImageWindLS, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWindLS, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWindLS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SkinTempLockCont = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_SkinTempLockCont);
    lv_obj_set_width(ui_SkinTempLockCont, 262);
    lv_obj_set_height(ui_SkinTempLockCont, 134);
    lv_obj_set_x(ui_SkinTempLockCont, -245);
    lv_obj_set_y(ui_SkinTempLockCont, 28);
    lv_obj_set_align(ui_SkinTempLockCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SkinTempLockCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_SkinTempLockCont);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -24);
    lv_obj_set_y(ui_Label12, -48);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "BABY TEMPERATURE:");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_SkinTempLockCont);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 24);
    lv_obj_set_y(ui_Label14, 3);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "37");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageBabyLS = lv_img_create(ui_SkinTempLockCont);
    lv_img_set_src(ui_ImageBabyLS, &ui_img_bebe_icon_png);
    lv_obj_set_width(ui_ImageBabyLS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageBabyLS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageBabyLS, -98);
    lv_obj_set_y(ui_ImageBabyLS, 2);
    lv_obj_set_align(ui_ImageBabyLS, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBabyLS, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageBabyLS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HumLockCont = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_HumLockCont);
    lv_obj_set_width(ui_HumLockCont, 262);
    lv_obj_set_height(ui_HumLockCont, 134);
    lv_obj_set_x(ui_HumLockCont, -245);
    lv_obj_set_y(ui_HumLockCont, 192);
    lv_obj_set_align(ui_HumLockCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HumLockCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label19 = lv_label_create(ui_HumLockCont);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -72);
    lv_obj_set_y(ui_Label19, -48);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "HUMIDITY:");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_HumLockCont);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -4);
    lv_obj_set_y(ui_Label20, 6);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "37");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImagenWaterLS = lv_img_create(ui_HumLockCont);
    lv_img_set_src(ui_ImagenWaterLS, &ui_img_302897630);
    lv_obj_set_width(ui_ImagenWaterLS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImagenWaterLS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImagenWaterLS, -83);
    lv_obj_set_y(ui_ImagenWaterLS, 6);
    lv_obj_set_align(ui_ImagenWaterLS, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImagenWaterLS, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImagenWaterLS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImagenWaterLS, 300);

    ui_HumLockDesiredCont = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_HumLockDesiredCont);
    lv_obj_set_width(ui_HumLockDesiredCont, 378);
    lv_obj_set_height(ui_HumLockDesiredCont, 134);
    lv_obj_set_x(ui_HumLockDesiredCont, 40);
    lv_obj_set_y(ui_HumLockDesiredCont, 192);
    lv_obj_set_align(ui_HumLockDesiredCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HumLockDesiredCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label23 = lv_label_create(ui_HumLockDesiredCont);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -20);
    lv_obj_set_y(ui_Label23, -48);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "TARGET HUMIDITY:");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_HumLockDesiredCont);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 15);
    lv_obj_set_y(ui_Label24, 6);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "37");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArrowHumLock = lv_img_create(ui_HumLockDesiredCont);
    lv_img_set_src(ui_ArrowHumLock, &ui_img_flecha_png);
    lv_obj_set_width(ui_ArrowHumLock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArrowHumLock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArrowHumLock, -155);
    lv_obj_set_y(ui_ArrowHumLock, 3);
    lv_obj_set_align(ui_ArrowHumLock, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArrowHumLock, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ArrowHumLock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ArrowHumLock, 100);

    ui_UnlockCont = lv_obj_create(ui_ScreenLock);
    lv_obj_remove_style_all(ui_UnlockCont);
    lv_obj_set_width(ui_UnlockCont, 310);
    lv_obj_set_height(ui_UnlockCont, 200);
    lv_obj_set_align(ui_UnlockCont, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UnlockCont, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_UnlockCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel11 = lv_obj_create(ui_UnlockCont);
    lv_obj_set_width(ui_Panel11, 300);
    lv_obj_set_height(ui_Panel11, 190);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_UnlockCont);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, 19);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "PRESS 2 SECS TO UNLOCK");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LockButton2 = lv_imgbtn_create(ui_UnlockCont);
    lv_imgbtn_set_src(ui_LockButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_candado_png, NULL);
    lv_obj_set_width(ui_LockButton2, 42);
    lv_obj_set_height(ui_LockButton2, 45);
    lv_obj_set_x(ui_LockButton2, 0);
    lv_obj_set_y(ui_LockButton2, -57);
    lv_obj_set_align(ui_LockButton2, LV_ALIGN_CENTER);

    ui_TargetSkinTempCont = lv_obj_create(ui_ScreenLock);
    lv_obj_remove_style_all(ui_TargetSkinTempCont);
    lv_obj_set_width(ui_TargetSkinTempCont, 378);
    lv_obj_set_height(ui_TargetSkinTempCont, 134);
    lv_obj_set_x(ui_TargetSkinTempCont, 40);
    lv_obj_set_y(ui_TargetSkinTempCont, 28);
    lv_obj_set_align(ui_TargetSkinTempCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TargetSkinTempCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TargetSkinTempLabel = lv_label_create(ui_TargetSkinTempCont);
    lv_obj_set_width(ui_TargetSkinTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TargetSkinTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TargetSkinTempLabel, 0);
    lv_obj_set_y(ui_TargetSkinTempLabel, -48);
    lv_obj_set_align(ui_TargetSkinTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TargetSkinTempLabel, "TARGET TEMPERATURE");
    lv_obj_set_style_text_color(ui_TargetSkinTempLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TargetSkinTempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TargetSkinTempLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TargetSkinTempLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TargetSkinTempLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TargetSkinTempNumLabel = lv_label_create(ui_TargetSkinTempCont);
    lv_obj_set_width(ui_TargetSkinTempNumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TargetSkinTempNumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TargetSkinTempNumLabel, 15);
    lv_obj_set_y(ui_TargetSkinTempNumLabel, 3);
    lv_obj_set_align(ui_TargetSkinTempNumLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TargetSkinTempNumLabel, "37");
    lv_obj_set_style_text_color(ui_TargetSkinTempNumLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TargetSkinTempNumLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TargetSkinTempNumLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArrowSkinLock = lv_img_create(ui_TargetSkinTempCont);
    lv_img_set_src(ui_ArrowSkinLock, &ui_img_flecha_png);
    lv_obj_set_width(ui_ArrowSkinLock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArrowSkinLock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArrowSkinLock, -130);
    lv_obj_set_y(ui_ArrowSkinLock, 3);
    lv_obj_set_align(ui_ArrowSkinLock, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArrowSkinLock, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ArrowSkinLock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ArrowSkinLock, 100);

    ui_Spinner1 = lv_arc_create(ui_ScreenLock);
    lv_obj_set_width(ui_Spinner1, 298);
    lv_obj_set_height(ui_Spinner1, 290);
    lv_obj_set_x(ui_Spinner1, 0);
    lv_obj_set_y(ui_Spinner1, 8);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Spinner1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_arc_set_value(ui_Spinner1, 50);

    ui_TargetAirTempCont = lv_obj_create(ui_ScreenLock);
    lv_obj_remove_style_all(ui_TargetAirTempCont);
    lv_obj_set_width(ui_TargetAirTempCont, 378);
    lv_obj_set_height(ui_TargetAirTempCont, 134);
    lv_obj_set_x(ui_TargetAirTempCont, 40);
    lv_obj_set_y(ui_TargetAirTempCont, -112);
    lv_obj_set_align(ui_TargetAirTempCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TargetAirTempCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TargetAirTempLabel = lv_label_create(ui_TargetAirTempCont);
    lv_obj_set_width(ui_TargetAirTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TargetAirTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TargetAirTempLabel, 0);
    lv_obj_set_y(ui_TargetAirTempLabel, -48);
    lv_obj_set_align(ui_TargetAirTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TargetAirTempLabel, "TARGET TEMPERATURE");
    lv_obj_set_style_text_color(ui_TargetAirTempLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TargetAirTempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TargetAirTempLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TargetAirTempLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TargetAirTempLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TargetAirTempNumLabel = lv_label_create(ui_TargetAirTempCont);
    lv_obj_set_width(ui_TargetAirTempNumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TargetAirTempNumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TargetAirTempNumLabel, 15);
    lv_obj_set_y(ui_TargetAirTempNumLabel, 3);
    lv_obj_set_align(ui_TargetAirTempNumLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TargetAirTempNumLabel, "37");
    lv_obj_set_style_text_color(ui_TargetAirTempNumLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TargetAirTempNumLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TargetAirTempNumLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArrowAirLock = lv_img_create(ui_TargetAirTempCont);
    lv_img_set_src(ui_ArrowAirLock, &ui_img_flecha_png);
    lv_obj_set_width(ui_ArrowAirLock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArrowAirLock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArrowAirLock, -130);
    lv_obj_set_y(ui_ArrowAirLock, 3);
    lv_obj_set_align(ui_ArrowAirLock, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArrowAirLock, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ArrowAirLock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ArrowAirLock, 100);

    ui_StatusCont = lv_obj_create(ui_ScreenLock);
    lv_obj_remove_style_all(ui_StatusCont);
    lv_obj_set_width(ui_StatusCont, 199);
    lv_obj_set_height(ui_StatusCont, 416);
    lv_obj_set_x(ui_StatusCont, 288);
    lv_obj_set_y(ui_StatusCont, 12);
    lv_obj_set_align(ui_StatusCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StatusCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StatusLabel = lv_label_create(ui_StatusCont);
    lv_obj_set_width(ui_StatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StatusLabel, -55);
    lv_obj_set_y(ui_StatusLabel, -173);
    lv_obj_set_align(ui_StatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StatusLabel, "STATUS:");
    lv_obj_set_style_text_color(ui_StatusLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatusLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmLockCont = lv_obj_create(ui_StatusCont);
    lv_obj_remove_style_all(ui_AlarmLockCont);
    lv_obj_set_width(ui_AlarmLockCont, 61);
    lv_obj_set_height(ui_AlarmLockCont, 60);
    lv_obj_set_x(ui_AlarmLockCont, 53);
    lv_obj_set_y(ui_AlarmLockCont, -174);
    lv_obj_set_align(ui_AlarmLockCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AlarmLockCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AlarmLockImg = lv_imgbtn_create(ui_AlarmLockCont);
    lv_imgbtn_set_src(ui_AlarmLockImg, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1007688293, NULL);
    lv_obj_set_width(ui_AlarmLockImg, 49);
    lv_obj_set_height(ui_AlarmLockImg, 45);
    lv_obj_set_x(ui_AlarmLockImg, -1);
    lv_obj_set_y(ui_AlarmLockImg, -2);
    lv_obj_set_align(ui_AlarmLockImg, LV_ALIGN_CENTER);

    ui_PanelLockAlarm = lv_obj_create(ui_AlarmLockCont);
    lv_obj_set_width(ui_PanelLockAlarm, 22);
    lv_obj_set_height(ui_PanelLockAlarm, 24);
    lv_obj_set_x(ui_PanelLockAlarm, 17);
    lv_obj_set_y(ui_PanelLockAlarm, -13);
    lv_obj_set_align(ui_PanelLockAlarm, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLockAlarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelLockAlarm, lv_color_hex(0xB50000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLockAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmLockNumLabel = lv_label_create(ui_AlarmLockCont);
    lv_obj_set_width(ui_AlarmLockNumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlarmLockNumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmLockNumLabel, 17);
    lv_obj_set_y(ui_AlarmLockNumLabel, -13);
    lv_obj_set_align(ui_AlarmLockNumLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AlarmLockNumLabel, "1");
    lv_obj_set_style_text_color(ui_AlarmLockNumLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AlarmLockNumLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckImg = lv_img_create(ui_StatusCont);
    lv_img_set_src(ui_CheckImg, &ui_img_check_png);
    lv_obj_set_width(ui_CheckImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckImg, 54);
    lv_obj_set_y(ui_CheckImg, -172);
    lv_obj_set_align(ui_CheckImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CheckImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_CheckImg, 300);

    lv_obj_add_event_cb(ui_AlarmLockImg, ui_event_AlarmLockImg, LV_EVENT_ALL, NULL);

}

void ui_ScreenLock_screen_destroy(void)
{
    if(ui_ScreenLock) lv_obj_del(ui_ScreenLock);

    // NULL screen variables
    ui_ScreenLock = NULL;
    ui_LockButton = NULL;
    ui_Container1 = NULL;
    ui_AirTempLockCont = NULL;
    ui_Label11 = NULL;
    ui_Label18 = NULL;
    ui_ImageWindLS = NULL;
    ui_SkinTempLockCont = NULL;
    ui_Label12 = NULL;
    ui_Label14 = NULL;
    ui_ImageBabyLS = NULL;
    ui_HumLockCont = NULL;
    ui_Label19 = NULL;
    ui_Label20 = NULL;
    ui_ImagenWaterLS = NULL;
    ui_HumLockDesiredCont = NULL;
    ui_Label23 = NULL;
    ui_Label24 = NULL;
    ui_ArrowHumLock = NULL;
    ui_UnlockCont = NULL;
    ui_Panel11 = NULL;
    ui_Label4 = NULL;
    ui_LockButton2 = NULL;
    ui_TargetSkinTempCont = NULL;
    ui_TargetSkinTempLabel = NULL;
    ui_TargetSkinTempNumLabel = NULL;
    ui_ArrowSkinLock = NULL;
    ui_Spinner1 = NULL;
    ui_TargetAirTempCont = NULL;
    ui_TargetAirTempLabel = NULL;
    ui_TargetAirTempNumLabel = NULL;
    ui_ArrowAirLock = NULL;
    ui_StatusCont = NULL;
    ui_StatusLabel = NULL;
    ui_AlarmLockCont = NULL;
    ui_AlarmLockImg = NULL;
    ui_PanelLockAlarm = NULL;
    ui_AlarmLockNumLabel = NULL;
    ui_CheckImg = NULL;

}
