// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface_Screen_PulseOxi

#include "ui.h"

lv_obj_t * ui_ScreenPulseOxi = NULL;
lv_obj_t * ui_ImgButton9 = NULL;
lv_obj_t * ui_OxCont = NULL;
lv_obj_t * ui_Panel15 = NULL;
lv_obj_t * ui_Label39 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_DetectOxi = NULL;
lv_obj_t * ui_OxiButton2 = NULL;
// event funtions
void ui_event_ImgButton9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMain_screen_init);
        _ui_screen_delete(&ui_ScreenPulseOxi);
    }
}

// build funtions

void ui_ScreenPulseOxi_screen_init(void)
{
    ui_ScreenPulseOxi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPulseOxi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton9 = lv_imgbtn_create(ui_ScreenPulseOxi);
    lv_imgbtn_set_src(ui_ImgButton9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1508956403, NULL);
    lv_obj_set_width(ui_ImgButton9, 50);
    lv_obj_set_height(ui_ImgButton9, 52);
    lv_obj_set_x(ui_ImgButton9, -360);
    lv_obj_set_y(ui_ImgButton9, -204);
    lv_obj_set_align(ui_ImgButton9, LV_ALIGN_CENTER);

    ui_OxCont = lv_obj_create(ui_ScreenPulseOxi);
    lv_obj_remove_style_all(ui_OxCont);
    lv_obj_set_width(ui_OxCont, 785);
    lv_obj_set_height(ui_OxCont, 443);
    lv_obj_set_x(ui_OxCont, -6);
    lv_obj_set_y(ui_OxCont, 54);
    lv_obj_set_align(ui_OxCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OxCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel15 = lv_obj_create(ui_OxCont);
    lv_obj_set_width(ui_Panel15, 336);
    lv_obj_set_height(ui_Panel15, 129);
    lv_obj_set_x(ui_Panel15, -198);
    lv_obj_set_y(ui_Panel15, -140);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label39 = lv_label_create(ui_OxCont);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, -296);
    lv_obj_set_y(ui_Label39, -183);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "Pulse Oximetry");

    ui_Label5 = lv_label_create(ui_OxCont);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -316);
    lv_obj_set_y(ui_Label5, -128);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "25.1");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DetectOxi = lv_label_create(ui_OxCont);
    lv_obj_set_width(ui_DetectOxi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DetectOxi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DetectOxi, -202);
    lv_obj_set_y(ui_DetectOxi, -129);
    lv_obj_set_align(ui_DetectOxi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DetectOxi, "25.1");
    lv_obj_set_style_text_font(ui_DetectOxi, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OxiButton2 = lv_btn_create(ui_OxCont);
    lv_obj_set_width(ui_OxiButton2, 310);
    lv_obj_set_height(ui_OxiButton2, 30);
    lv_obj_set_x(ui_OxiButton2, -206);
    lv_obj_set_y(ui_OxiButton2, -183);
    lv_obj_set_align(ui_OxiButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OxiButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_OxiButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_opa(ui_OxiButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_OxiButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton9, ui_event_ImgButton9, LV_EVENT_ALL, NULL);

}

void ui_ScreenPulseOxi_screen_destroy(void)
{
    if(ui_ScreenPulseOxi) lv_obj_del(ui_ScreenPulseOxi);

    // NULL screen variables
    ui_ScreenPulseOxi = NULL;
    ui_ImgButton9 = NULL;
    ui_OxCont = NULL;
    ui_Panel15 = NULL;
    ui_Label39 = NULL;
    ui_Label5 = NULL;
    ui_DetectOxi = NULL;
    ui_OxiButton2 = NULL;

}
