// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface_Screen_Alarms

#ifndef _ESP32HMIINTERFACE_SCREEN_ALARMS_UI_H
#define _ESP32HMIINTERFACE_SCREEN_ALARMS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_ScreenAlarms.h"
#include "ui_ScreenMain.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1508956403);    // assets/back icon (1).png
LV_IMG_DECLARE(ui_img_mute_icon_png);    // assets/mute_icon.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
