// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface_Screen1

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Incunest;
extern void ui_event_Settings(lv_event_t * e);
extern lv_obj_t * ui_Settings;
extern void ui_event_AlarmButton(lv_event_t * e);
extern lv_obj_t * ui_AlarmButton;
extern lv_obj_t * ui_TempCont;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_AirPanelCont;
extern lv_obj_t * ui_AirPanel;
extern lv_obj_t * ui_TempAirDetected;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_AirTempBarCont;
extern lv_obj_t * ui_TempAirDetectedRight;
extern lv_obj_t * ui_TempAirDesired;
extern lv_obj_t * ui_AirTempBar;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_SkinPanelCont;
extern lv_obj_t * ui_SkinPanel;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_TempSkinDetected;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_SkinTempBarCont;
extern lv_obj_t * ui_SkinTempBar;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_TempSkinDetectedRight;
extern lv_obj_t * ui_TempSkinDesired;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_ArrowDownTemp;
extern lv_obj_t * ui_ArrowUpTemp;
extern lv_obj_t * ui_ImgArrowDownTemp;
extern lv_obj_t * ui_ImgArrowUpTemp;
extern lv_obj_t * ui_TempButton;
extern lv_obj_t * ui_HumCont;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_HumPanelCont;
extern lv_obj_t * ui_HumDetected;
extern lv_obj_t * ui_HumBar;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_ArrowUpHum;
extern lv_obj_t * ui_ArrowDownHum;
extern lv_obj_t * ui_HumDetectedRight;
extern lv_obj_t * ui_HumDesired;
extern lv_obj_t * ui_ImgArrowUpHum;
extern lv_obj_t * ui_ImgArrowDownHum;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_HumidButton;
extern lv_obj_t * ui_HumidityLabel;
extern lv_obj_t * ui_PhotoCont;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_PhototherapyLabel;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_NumAlarm;
extern void ui_event_SPO2Button(lv_event_t * e);
extern lv_obj_t * ui_SPO2Button;
extern void ui_event_ChartButton(lv_event_t * e);
extern lv_obj_t * ui_ChartButton;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Tempbutton;
extern lv_obj_t * uic_HumidButton;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

