// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface_Screen_PulseOxi

#ifndef UI_ScreenMain_H
#define UI_ScreenMain_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenMain
extern void ui_ScreenMain_screen_init(void);
extern void ui_ScreenMain_screen_destroy(void);
extern lv_obj_t * ui_ScreenMain;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

