// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel12;
extern void ui_event_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Switch2;
extern void ui_event_Switch3(lv_event_t * e);
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label6;
extern void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern void ui_event_Panel6(lv_event_t * e);
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern void ui_event_Panel7(lv_event_t * e);
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_ImgButton3;
extern lv_obj_t * ui_ImgButton4;
extern lv_obj_t * ui_ImgButton5;
extern lv_obj_t * ui_ImgButton6;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label33;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

