// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32HMIInterface

#ifndef UI_ScreenSettings_H
#define UI_ScreenSettings_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenSettings
extern void ui_ScreenSettings_screen_init(void);
extern void ui_ScreenSettings_screen_destroy(void);
extern lv_obj_t * ui_ScreenSettings;
extern lv_obj_t * ui_Label8;
extern void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

